import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "./provider";


export const metadata: Metadata = {
  title: "SpotTube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com"/>
<link href="https://fonts.googleapis.com/css2?family=Eater&family=Fascinate&family=Monoton&display=swap" rel="stylesheet"></link>
      </head>
      <body>
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
